"""Modified columns in Student database and added more

Revision ID: 3da06e95a45f
Revises: 66218265323b
Create Date: 2021-09-10 13:14:11.575255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3da06e95a45f'
down_revision = '66218265323b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('admission_date', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('middle_name', sa.String(length=64), nullable=True))
    op.add_column('students', sa.Column('gender', sa.CHAR(length=1), nullable=True))
    op.add_column('students', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('marital_status', sa.String(length=16), nullable=True))
    op.add_column('students', sa.Column('country', sa.String(length=64), nullable=True))
    op.add_column('students', sa.Column('residence_state', sa.String(length=64), nullable=True))
    op.add_column('students', sa.Column('residence_local_govt', sa.String(length=64), nullable=True))
    op.add_column('students', sa.Column('origin_state', sa.String(length=64), nullable=True))
    op.add_column('students', sa.Column('origin_local_govt', sa.String(length=64), nullable=True))
    op.drop_index('ix_students_department', table_name='students')
    op.drop_index('ix_students_level', table_name='students')
    op.drop_column('students', 'department')
    op.drop_column('students', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('level', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('department', mysql.VARCHAR(length=128), nullable=False))
    op.create_index('ix_students_level', 'students', ['level'], unique=False)
    op.create_index('ix_students_department', 'students', ['department'], unique=False)
    op.drop_column('students', 'origin_local_govt')
    op.drop_column('students', 'origin_state')
    op.drop_column('students', 'residence_local_govt')
    op.drop_column('students', 'residence_state')
    op.drop_column('students', 'country')
    op.drop_column('students', 'marital_status')
    op.drop_column('students', 'birth_date')
    op.drop_column('students', 'gender')
    op.drop_column('students', 'middle_name')
    op.drop_column('students', 'admission_date')
    # ### end Alembic commands ###
