"""Added user roles

Revision ID: 58dea9137062
Revises: e17df50f895f
Create Date: 2021-09-12 10:46:46.692889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58dea9137062'
down_revision = 'e17df50f895f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('urole', sa.String(length=15), nullable=True, default='Student'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'urole')
    # ### end Alembic commands ###
