"""First revision script

Created table, added constraints and created indexes

Revision ID: 66218265323b
Revises: 
Create Date: 2021-09-06 21:03:43.665276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66218265323b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('reg_number', sa.String(length=32), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', 'reg_number')
    )
    op.create_index(op.f('ix_students_department'), 'students', ['department'], unique=False)
    op.create_index(op.f('ix_students_level'), 'students', ['level'], unique=False)
    op.create_index(op.f('ix_students_reg_number'), 'students', ['reg_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_reg_number'), table_name='students')
    op.drop_index(op.f('ix_students_level'), table_name='students')
    op.drop_index(op.f('ix_students_department'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
