"""Once again, another overhaul of the models. This time, role implementation seems to be going smooth.

Revision ID: c4910f0d7660
Revises: df15d965dd3d
Create Date: 2021-09-13 11:59:54.991470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4910f0d7660'
down_revision = 'df15d965dd3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecturer',
    sa.Column('acc_role', sa.String(length=10), nullable=True),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('middle_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.CHAR(length=1), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(length=15), nullable=True),
    sa.Column('home_address', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('superadmin',
    sa.Column('acc_role', sa.String(length=10), nullable=True),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('middle_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.CHAR(length=1), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(length=15), nullable=True),
    sa.Column('home_address', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('admin', sa.Column('acc_role', sa.String(length=10), nullable=True))
    op.add_column('admin', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_column('admin', 'admission_date')
    op.drop_column('admin', 'urole')
    op.add_column('student', sa.Column('acc_role', sa.String(length=10), nullable=True))
    op.drop_column('student', 'is_active')
    op.drop_column('student', 'admission_date')
    op.drop_column('student', 'urole')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('urole', mysql.VARCHAR(length=15), nullable=True))
    op.add_column('student', sa.Column('admission_date', sa.DATE(), nullable=True))
    op.add_column('student', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('student', 'acc_role')
    op.add_column('admin', sa.Column('urole', mysql.VARCHAR(length=15), nullable=True))
    op.add_column('admin', sa.Column('admission_date', sa.DATE(), nullable=True))
    op.drop_column('admin', 'is_admin')
    op.drop_column('admin', 'acc_role')
    op.drop_table('superadmin')
    op.drop_table('lecturer')
    # ### end Alembic commands ###
