"""Complete overhaul of models

Revision ID: df15d965dd3d
Revises: 58dea9137062
Create Date: 2021-09-12 15:09:25.796703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df15d965dd3d'
down_revision = '58dea9137062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('urole', sa.String(length=15), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('middle_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.CHAR(length=1), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(length=15), nullable=True),
    sa.Column('home_address', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('student',
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('urole', sa.String(length=15), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('middle_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.CHAR(length=1), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(length=15), nullable=True),
    sa.Column('home_address', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('admission_date', sa.DATE(), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('middle_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('gender', mysql.CHAR(length=1), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('marital_status', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('home_address', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('residence_state', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('residence_local_govt', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('origin_state', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('origin_local_govt', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('urole', mysql.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('student')
    op.drop_table('admin')
    # ### end Alembic commands ###
