"""Dropped students and went for User model with Roles approach

Revision ID: e17df50f895f
Revises: 451aeeffda38
Create Date: 2021-09-10 19:34:39.317862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e17df50f895f'
down_revision = '451aeeffda38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.CHAR(length=1), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(length=16), nullable=True),
    sa.Column('home_address', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('residence_state', sa.String(length=64), nullable=True),
    sa.Column('residence_local_govt', sa.String(length=64), nullable=True),
    sa.Column('origin_state', sa.String(length=64), nullable=True),
    sa.Column('origin_local_govt', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_index('ix_students_reg_number', table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('reg_number', mysql.CHAR(length=9), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('admission_date', sa.DATE(), nullable=True),
    sa.Column('middle_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('gender', mysql.CHAR(length=1), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('marital_status', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('residence_state', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('residence_local_govt', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('origin_state', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('origin_local_govt', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('home_address', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_students_reg_number', 'students', ['reg_number'], unique=False)
    op.drop_table('users')
    # ### end Alembic commands ###
